export { default as waves } from './waves.png'
export { default as arrowLeft } from './arrow-left.svg'
export { default as arrowRight } from './arrow-right.svg'
export { default as exampleQr } from './example-qr.png'
export { default as greenCircle } from './green-circle.svg'
export { default as grayCicrcle } from './gray-circle.svg'
export { default as widget } from './widget.png'
